[technote]
id = "DMTN-279"
series_id = "DMTN"
canonical_url = "https://dmtn-279.lsst.io"
github_url = "https://github.com/lsst-dm/dmtn-279"
github_default_branch = "main"
date_created = 2024-01-16T21:30:53Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Christine"
name.family = "Banek"
orcid = ""
internal_id = "banekc"
[[technote.authors.affiliations]]
name = "Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ  85719, USA"
